"""strain/l5 — the prospection blocking seam: two tiers no cue can address.

`PULSE` (`BOUNDARY.log` line 34) audited `strain/l5` against `autopsy/GAPMAP.md
§6`'s seven-sin catalog and found **one genuine gap**, the post-L4 finding one
tier wider:

> *"**BLOCKING is UNCOVERED at Layer 5.** `README-l5 §4` states in prose that
> neither the pending set nor the fired ledger is reachable by cue — `recall`
> runs over the handle index of retained EPISODES and neither tier is one — and
> the `DOGFOOD` session measured the shell half of it … but NO strain trial
> measures the Layer-5 cue reach on the binding corpus the way
> `strain/l4::trial_a_demoted_assertion_keeps_its_content_and_loses_its_cue`
> measured 26‰ for demoted content. A Layer-5 blocking strain over the two new
> tiers is RECOMMENDED, not ruled."*

The recommendation loop is known to work: the post-L4 `PULSE` recommended
exactly this shape one layer down, and the `[L4] [STRAIN]` session
(`BOUNDARY.log` line 26) closed it **and found a real engine defect on the way**.
This file is that loop's second turn, in the same established form — measured on
the binding corpus at the ratified cap, stated over the tiers the layer actually
adds, and pinned so the behaviour cannot change silently **in either direction**.

| strain | class | what would otherwise fail quietly |
|---|---|---|
| an armed intention is `t`-addressable and has no cue address at all | **blocking** (Schacter; `autopsy/GAPMAP.md §6`) | an access channel that is not narrow but absent, described in prose and nowhere in a number |
| a fired event is regenerated by `t` and is in no index | **blocking**, on the tier the engine writes itself | the first content this engine emits rather than receives, reachable by nothing but its own clock |
| a kept promise is booked; an unkept one regenerates | **absent-mindedness** / **recorded-but-never-binding** | either half of an asymmetry two real defects have already sat on |

## What the L4 seam measured, and how this one differs

`strain/l4` found demoted content `t`-addressable and **not** cue-addressable and
put the number the prose never carried at **26‰** — the cue channel reaching the
498 held episodes of 19 286 answerable events. The cause there was **the budget**:
`README-l4 §0.1` proved that at a 250‰ footprint exactly one access path is
affordable, and the associative one is the path the budget does not buy.

At Layer 5 the number is **51‰** (952 held of 18 724 answerable) and the cause is
**not** the budget for either new tier. Both are stated separately because they
fail for different reasons, and a strain that ran them together would report one
finding where there are two:

* **the armed tier** — a payload is **cue-addressable or an intention, never
  both**. `recall` addresses an episode by a `HANDLE_FIELDS` atom
  (`tag`/`id`/`entity`/`sid`/`src`/`dst`, `README-l3 §0.2`); the frozen `intend`
  grammar carries none of them, and `README-l5 §1.2` arms a payload only if it
  rebuilds from `(iid, cond, fire)` as **canonical bytes**, so adding one is
  exactly what stops it arming. That is the engine-side form of the `DOGFOOD`
  field note (`FIELD.md`, 2026-08-01, *intend (the schema)*: adding `tok` leaves
  the payload perfectly canonical and stops it arming), and it is sharper: the
  rule that **opens** the capability is the rule that closes the channel.
* **the fired tier** — the closure is the **tier**, not the grammar. A fired
  event is folded and its episode released into the fired ledger, which
  regenerates it; it is never stored as an episode, so it never earns a posting.
  A fire payload that *does* carry a handle field is still unreachable, while an
  ordinary event carrying the same one is reached exactly — which is what turns
  "neither tier is an episode" from a sentence into a measurement.

## The asymmetry the field measured, made behaviour

`FIELD.md` (2026-08-01, *the consolidation boundary*) found, out of suite on a
copy of the real store, that **a promise is readable exactly as long as it is
unkept**: at 8 000 cells a fired intention's own `intend` event is taken back and
`read(t0)` returns it byte-exact, at 7 000 there is no room and it is booked into
the forgetting record, while the still-pending intention beside it stays
byte-exact at the same cap. That was a finding. The third strain makes it
behaviour, in **both** directions, because the project has already committed a
defect on each side:

* booking a loss as a lossless demotion — `BOUNDARY.log` line 26, the atlas-None
  seam, `autopsy/GAPMAP.md §2`'s *recorded but never binding* landing on the one
  structure whose job is to say what is gone;
* releasing what nothing forced a drop of — `BOUNDARY.log` line 32, the first
  Stage-C engine, which released an armed intention's episode **unconditionally**
  and lost 765 `intend` events at a generous budget: a Layer-1 regression
  invisible to every `§5 L5` clause, because the gate scores firings and not the
  `intend` events themselves.

## Why this file declares no gate constant

`strain/l4`'s copy of `GATE_FOOTPRINT` is in `laws/t_rulings.py` because a §5
number cannot appear in a trial without a recorded authority whatever the trial
does with it. `§5 L5` states **no** footprint clause and `R6` clause 4's cap is a
*ratio* over the corpus — `budget_cap = raw_cells // 4 = 45 638` — so the pressure
these strains are stated at is read from `_l5tasks` rather than typed, and there
is no constant to register.

**The bill, stated rather than discovered.** One whole-stream replay of
`corpora/l5stream` at the ratified cap (~21 s) plus one `read(t)` census of all
20 765 logical times (~2 s), both built once and shared by all four trials; the
generous-cap direction is a 4 000-event prefix of the same frozen bytes and costs
under a second, the prefix ladder being the form `humility/l4` established for
measuring the same bytes at a second scale.
"""

import os
from fractions import Fraction

from _harness import require, require_equal
from adapters import l5
import _l5score
import _l5tasks
from core.serialize import encode
from core.state import event_cost

BINDING = "l5stream"
LAYER_CAP = 5

# The generous-cap direction of the kept-promise asymmetry, on a prefix of the
# same frozen bytes. 4 000 is `strain/l5`'s existing determinism prefix, reused
# so the two files pressure the same slice of the corpus at two different caps.
PREFIX_EVENTS = 4000

# The cue channel's reach must stay far below the `t` channel's for the blocking
# claim to be under test at all — the `strain/l4` discipline (`a fixture that
# applies no real demotion pressure is not testing the claim`), stated here as a
# permille bound rather than as a pinned count, because the pinned counts belong
# to `anchors/l5.json` and the README note.
REACH_CEILING = 100

_RUNS = {}


# ---- the shared run ---------------------------------------------------------

def _at_the_gate():
    """`corpora/l5stream` replayed at the ratified Layer-5 cap, once per run."""
    if "gate" not in _RUNS:
        b = _l5tasks.corpus()
        state, budget = _l5score.replay(
            l5, lambda cap: l5.make_engine(LAYER_CAP, cap), b)
        require_equal(budget["refused"], 0,
                      "a caller write was refused at the ratified cap, so the "
                      "stream this file measures is not the stream the corpus "
                      "declares")
        _RUNS["gate"] = (state, budget, b)
    return _RUNS["gate"]


def _census():
    """Split every assigned `t` into held / regenerated / gone, by what §7 says.

    The classification is read off the ordinary query interface and nothing else,
    exactly as `strain/l4::_partition` reads it: `read(t)` either abstains
    (**gone**) or answers with a provenance kind of `recall` (still a stored
    episode: **held**) or `derive` (something regenerated it: **derived**). The
    two kinds are what make the blocking claim measurable from outside — the
    engine is not merely right, it says which channel it was right from.
    """
    if "census" not in _RUNS:
        state, _budget, _b = _at_the_gate()
        held, derived, gone = set(), set(), set()
        for t in range(state.next_t):
            answer = l5.query(state, {"op": "read", "t": t})
            if answer["status"] == "abstain":
                gone.add(t)
                continue
            if answer["provenance"]["kind"] == "recall":
                held.add(t)
            else:
                derived.add(t)
        _RUNS["census"] = (held, derived, gone)
    return _RUNS["census"]


def _t0(b, iid):
    """The logical time the intention `iid` was written at."""
    return b["caller_t"][b["intents"][iid]["k0"]]


def _intend_payload(b, iid):
    return b["payloads"][b["intents"][iid]["k0"]]


def _replay(payloads, cap):
    """Ingest a fixture at `cap`, asserting the budget law after every write."""
    state = l5.make_engine(LAYER_CAP, cap)
    refused = []
    for i, payload in enumerate(payloads):
        state, t = l5.ingest(state, payload)
        if t is None:
            refused.append(i)
        require(state.occupancy <= cap,
                "occupancy %d exceeded the cap %d at write %d — the budget law "
                "broke mid-stream (§4.1)" % (state.occupancy, cap, i))
    return state, refused


def _reach():
    """`(held, answerable, permille)` — the cue channel's share of the `t` channel."""
    held, derived, _gone = _census()
    answerable = len(held) + len(derived)
    return len(held), answerable, _l5tasks.permille(
        Fraction(len(held), answerable))


# ---- 1. the armed tier ------------------------------------------------------

def trial_an_armed_intention_keeps_its_content_and_was_never_cue_addressable():
    """**Blocking**, over the tier that holds a promise nobody has kept yet.

    `README-l5 §4` states it in prose: *"No recall of a pending intention or of an
    emitted event. Both are regenerated by `read(t)` and neither is reachable by
    cue: `recall` runs over the handle index of retained episodes, and neither
    tier is one."* Measured on the binding corpus at the ratified cap, where 180
    intentions nothing satisfies are still pending at stream end:

      (a) **content survives, addressed by `t`.** Every pending intention's own
          `intend` event comes back **byte-exact** from `read(t0)`, tagged
          `derive` and never `recall` — the pending entry regenerates it, which
          is what makes releasing its episode at the door a demotion and not a
          loss (`README-l5 §1.3`).
      (b) **there is no cue to lose, and the abstention is honest.** Not one cue
          built from a pending intention's own payload is answered, and not one
          is answered *wrongly*: `recall` abstains (§3.0 pays 100) rather than
          reaching for the nearest retained neighbour (§3.0 pays 0). A bare
          `{"kind":"intend","iid":I}` probe is asserted beside the whole payload,
          so the claim is about the address and not about the probe's width.
      (c) **the index still works.** All 952 held episodes are reached exactly by
          their own content, so (b) measures a channel that does not exist and
          not an index this trial broke.

    **The cause, isolated rather than asserted.** At Layer 4 the closure was the
    budget. Here it is the rule that opens the capability: `recall` addresses an
    episode by a `HANDLE_FIELDS` atom, the frozen `intend` grammar carries none,
    and `README-l5 §1.2` arms only a payload that rebuilds from `(iid, cond,
    fire)` as canonical bytes — so a would-be intention carrying `entity` is
    **retained as an ordinary episode and reached exactly**, and arms nothing. A
    payload is **cue-addressable or an intention, never both**, and the fixture at
    the end of this trial is where that is a measurement.
    """
    state, _budget, b = _at_the_gate()
    held, _derived, _gone = _census()

    pending = l5.pending_iids(state)
    require_equal(len(pending), len(b["never"]),
                  "the pending set does not carry every never-fires intention, "
                  "so this trial is not measuring the tier it claims to")

    # (a) content survives, addressed by `t`, and says which channel it came from.
    for iid in pending:
        t0 = _t0(b, iid)
        answer = l5.query(state, {"op": "read", "t": t0})
        require_equal(answer["status"], "answer",
                      "intention %d is still pending, so the pending entry "
                      "regenerates its own `intend` event — read(%d) abstained"
                      % (iid, t0))
        require_equal(answer["value"], {"payload": _intend_payload(b, iid),
                                       "t": t0},
                      "a pending intention's own event did not come back "
                      "byte-exact from read(%d)" % (t0,))
        require_equal(answer["provenance"]["kind"], "derive",
                      "read(%d) answered a pending intention's event as a stored "
                      "episode (`recall`). Arming releases that episode at the "
                      "door because the pending entry regenerates it, so a "
                      "`recall` here means the release did not happen and the "
                      "cells this layer priced are being spent twice" % (t0,))

    # (b) a cue drawn from a pending intention: no address, and never wrong.
    blocked = 0
    misdirected = []
    for iid in pending:
        payload = _intend_payload(b, iid)
        for cue in (payload, {"kind": "intend", "iid": iid}):
            answer = l5.query(state, {"op": "recall", "cue": cue})
            if answer["status"] == "abstain":
                blocked += 1
                continue
            misdirected.append((iid, cue, answer["value"]["t"]))
    require(not misdirected,
            "recall answered a cue drawn from a pending intention: %r — the "
            "abstention is the honesty here, and a confident neighbour scores 0 "
            "under §3.0 where an abstention keeps 100" % (misdirected[:5],))
    require_equal(blocked, 2 * len(pending),
                  "%d of %d probes over the pending set were answered — the seam "
                  "this strain pins is not where README-l5 §4 says it is"
                  % (2 * len(pending) - blocked, 2 * len(pending)))

    # (c) the held episodes are still reached exactly, so (b) is a missing channel.
    unreachable = []
    for t in sorted(held):
        cue = l5.query(state, {"op": "read", "t": t})["value"]["payload"]
        answer = l5.query(state, {"op": "recall", "cue": cue})
        if answer["status"] == "answer" and answer["value"]["t"] == t:
            continue
        unreachable.append(t)
    require(not unreachable,
            "held episodes %r are not reachable by their own content — the cue "
            "channel is broken rather than absent over the prospection tiers, "
            "and (b) would be vacuous" % (unreachable[:5],))

    # The price, as a number: what the two new tiers cost the cue channel.
    reached, answerable, permille = _reach()
    require(permille <= REACH_CEILING,
            "the cue channel reaches %d of %d answerable events (%d‰) — this run "
            "applies no real pressure, so the blocking claim is not under test"
            % (reached, answerable, permille))
    require_equal(len(held & {_t0(b, iid) for iid in pending}), 0,
                  "a pending intention's own event is a held episode, so the "
                  "prospection tier is not the only thing holding it")

    # The cause, isolated: cue-addressable or an intention, never both.
    plain = {"kind": "intend", "iid": 1,
             "cond": {"p": "kind", "v": "note"},
             "fire": {"kind": "fired", "text_id": 900}}
    addressable = {"kind": "intend", "entity": 4, "iid": 1,
                   "cond": {"p": "kind", "v": "note"},
                   "fire": {"kind": "fired", "text_id": 900}}
    require(l5.arms(plain) is not None,
            "the control payload does not arm, so the fixture proves nothing "
            "about what arming costs")
    require(l5.arms(addressable) is None,
            "an `intend` payload carrying a HANDLE_FIELDS member still arms — "
            "then a promise could be cue-addressable, and README-l5 §1.2's "
            "canonical-bytes rule is not doing what this seam rests on")
    note = {"kind": "note", "entity": 4, "text_id": 1}
    fixture = [addressable, note]
    state2, refused2 = _replay(fixture, 8 * sum(event_cost(p) for p in fixture))
    require_equal(refused2, [], "an in-budget write was refused")
    require_equal(l5.pending_iids(state2), [],
                  "the handle-bearing payload armed an intention after all")
    answer = l5.query(state2, {"op": "read", "t": 0})
    require_equal(answer["provenance"]["kind"], "recall",
                  "the unarmed payload was not retained as an ordinary episode, "
                  "so the counterfactual does not isolate the address")
    answer = l5.query(state2, {"op": "recall", "cue": addressable})
    require_equal(answer["status"], "answer",
                  "the same payload, one field wider and therefore NOT an "
                  "intention, is still unreachable by cue — then the closure is "
                  "not the address and this trial names the wrong cause")
    require_equal(answer["value"]["t"], 0,
                  "the handle-bearing payload was reached at the wrong `t`")


# ---- 2. the fired tier ------------------------------------------------------

def trial_a_fired_event_is_regenerated_by_t_and_lives_in_no_index():
    """**Blocking**, over the first content this engine emits rather than receives.

    A firing is an event at a logical time of its own (`R6` clause 2) and it is
    the one kind of event no caller wrote. `README-l5 §1.4` releases its episode
    into the fired ledger, which regenerates it — so it is never stored as an
    episode, and an episode is the only thing `recall` addresses. Measured on the
    binding corpus at the ratified cap over all 765 firings:

      (a) every fired event comes back **byte-exact** from `read(t_fire)` as the
          payload the caller wrote into the intention, tagged `derive` and never
          `recall` (§1.4: *"the engine adds nothing to an event but its `t`"*);
      (b) not one cue built from a fired payload is answered, and none wrongly;
      (c) no firing's `t` is in the held set at all.

    **The cause is the tier, not the grammar — and that is the asymmetry with the
    armed tier one trial up.** The fixture proves it by handing a fire payload a
    handle field the `intend` grammar could never carry: the firing is still
    unreachable, while an ordinary event carrying the *same* atom is reached
    exactly by it. So the cluster exists, the index works, and the firing is
    simply not in it — which is `README-l5 §4`'s *"neither tier is one"* as a
    measurement rather than a sentence.
    """
    state, _budget, b = _at_the_gate()
    held, _derived, _gone = _census()

    fired = l5.fired_iids(state)
    require_equal(len(fired), len(b["fireable"]),
                  "the fired ledger does not carry every fireable intention")

    blocked = 0
    misdirected = []
    for iid in fired:
        records = l5.fired_by(state, iid)
        require(records is not None and len(records) == 1,
                "intention %d did not fire exactly once: %r" % (iid, records))
        t_fire = records[0]["t"]
        fire = b["intents"][iid]["fire"]

        answer = l5.query(state, {"op": "read", "t": t_fire})
        require_equal(answer["status"], "answer",
                      "read(%d) abstained on an event the engine itself emitted"
                      % (t_fire,))
        require_equal(answer["value"], {"payload": fire, "t": t_fire},
                      "the fired event at t=%d is not the payload the caller "
                      "wrote into intention %d" % (t_fire, iid))
        require_equal(answer["provenance"]["kind"], "derive",
                      "read(%d) answered a fired event as a stored episode "
                      "(`recall`) — the fired ledger is its derived view, and an "
                      "episode beside it would be the redundant copy this layer "
                      "priced away" % (t_fire,))
        require(t_fire not in held,
                "the firing at t=%d is a held episode, so it would earn a "
                "posting and this trial measures nothing" % (t_fire,))

        answer = l5.query(state, {"op": "recall", "cue": fire})
        if answer["status"] == "abstain":
            blocked += 1
            continue
        misdirected.append((iid, t_fire, answer["value"]["t"]))
    require(not misdirected,
            "recall answered a cue drawn from a fired event: %r — an emitted "
            "event that answered a cue would be reachable by a channel §0.1 "
            "never bought" % (misdirected[:5],))
    require_equal(blocked, len(fired),
                  "%d of %d fired events were reachable by their own content"
                  % (len(fired) - blocked, len(fired)))

    # The cause, isolated: the tier, not the grammar.
    fire = {"entity": 3, "kind": "fired", "text_id": 77}
    fixture = [{"kind": "intend", "iid": 1, "cond": {"p": "kind", "v": "note"},
                "fire": fire},
               {"kind": "note", "entity": 3, "text_id": 500}]
    state2, refused2 = _replay(fixture, 8 * sum(event_cost(p) for p in fixture))
    require_equal(refused2, [], "an in-budget write was refused")
    records = l5.fired_by(state2, 1)
    require(records is not None and len(records) == 1,
            "the fixture's intention did not fire exactly once: %r" % (records,))
    t_fire = records[0]["t"]
    answer = l5.query(state2, {"op": "read", "t": t_fire})
    require_equal(answer["value"], {"payload": fire, "t": t_fire},
                  "the handle-bearing fired payload did not come back byte-exact")
    require_equal(answer["provenance"]["kind"], "derive",
                  "the handle-bearing fired event was stored as an episode, so "
                  "the counterfactual no longer isolates the tier")
    require_equal(l5.query(state2, {"op": "recall", "cue": fire})["status"],
                  "abstain",
                  "a fired event carrying a handle field IS reachable by cue — "
                  "then the closure over the fired tier is the grammar's and not "
                  "the tier's, and this trial names the wrong cause")
    # …while an ordinary event carrying the same atom is reached exactly by it.
    answer = l5.query(state2, {"op": "recall", "cue": {"entity": 3}})
    require_equal(answer["status"], "answer",
                  "the handle atom the fired payload carries reaches nothing at "
                  "all, so the fixture shows a missing cluster rather than a "
                  "missing posting")
    require_equal(answer["value"]["t"], 1,
                  "the shared handle atom did not reach the ordinary event that "
                  "carries it")
    require_equal(encode(answer["value"]["payload"]),
                  encode(fixture[1]),
                  "the shared handle atom reached something other than the "
                  "ordinary event")


# ---- 3. the kept-promise asymmetry ------------------------------------------

def trial_a_kept_promise_is_booked_and_an_unkept_one_still_regenerates():
    """`FIELD.md`'s finding made behaviour, in **both** directions.

    *A promise is readable exactly as long as it is unkept.* Arming releases the
    `intend` episode at the door because the pending entry regenerates it; firing
    consumes that derivation, so the episode is offered back to the store where
    the budget **already** has room and is otherwise booked into the forgetting
    record while the demotion counter gives it back (`README-l5 §1.3`).

    **Under pressure — the binding corpus at the ratified cap.** All 765 fired
    intentions' own events are gone and every one of them is **in the record**:
    `read(t0)` abstains, `forgot_at(t0)` carries a count, the record's count is
    exactly the set of `t` the engine abstains on, and its mass is never less
    than its count (`strain/l4`'s law: every loss carries at least its own
    weight). The number with teeth is the counterfactual: strip the promises out
    and the record reads 765 short — which is precisely the shape of the defect
    `BOUNDARY.log` line 26 found one layer down, a loss booked as compression by
    the one structure whose job is to say what is gone.

    A promise's weight in that record is always **1**, and cannot be otherwise: a
    payload declaring `importance` carries a fourth field, so `README-l5 §1.2`'s
    canonical-bytes rule stops it arming. **An intention cannot buy itself
    priority** — the same rule that denies it a cue surface denies it a weight,
    and both are asserted here rather than described.

    **Where there is room — the same frozen bytes at a generous cap.** On a
    4 000-event prefix at four times its own footprint, every fired intention's
    own event is **taken back** (`read(t0)` answers it byte-exact, tagged
    `recall`, as a stored episode), every pending one still regenerates
    (`derive`), and nothing at all is forgotten. That direction is not decoration:
    the first Stage-C engine released an armed intention's episode
    **unconditionally** and lost 765 `intend` events at a generous budget with
    nothing forcing a drop — a Layer-1 regression invisible to every `§5 L5`
    clause, because the gate scores firings and not the `intend` events
    themselves (`BOUNDARY.log` line 32).

    Both halves are asserted at once so that neither can be traded for the other:
    an engine that books what it had room for fails the second, an engine that
    keeps a booking firing made false fails the first.
    """
    state, _budget, b = _at_the_gate()
    _held, _derived, gone = _census()

    fired = l5.fired_iids(state)
    pending = l5.pending_iids(state)
    promises = {_t0(b, iid) for iid in fired}

    # --- under pressure: the promise is kept and its episode is booked -------
    unbooked = []
    still_held = []
    for iid in fired:
        t0 = _t0(b, iid)
        answer = l5.query(state, {"op": "read", "t": t0})
        if answer["status"] == "answer":
            still_held.append(iid)
            continue
        booked = l5.query(state, {"op": "forgot_at", "t": t0})
        if booked["status"] != "answer" or booked["value"]["count"] < 1:
            unbooked.append(iid)
            continue
        require(booked["value"]["mass"] >= booked["value"]["count"],
                "the bucket carrying intention %d's released episode records "
                "%d losses at %d mass — every loss carries at least its own "
                "weight, so a bucket with less mass than count has lost a loss"
                % (iid, booked["value"]["count"], booked["value"]["mass"]))
    require(not unbooked,
            "%d fired intentions left their own `intend` episode unreadable and "
            "UNBOOKED (%s): the episode was released at arming as a demotion "
            "because the pending entry regenerated it, and firing is what makes "
            "that booking false (BOUNDARY.log line 26, one layer down)"
            % (len(unbooked), unbooked[:8]))
    require_equal(still_held, [],
                  "%d fired intentions' own events are still readable at the "
                  "ratified cap. That is lawful where the budget has room — and "
                  "at this cap it has 10 cells, so a non-zero count here means "
                  "the pressure half of this asymmetry is no longer under test"
                  % (len(still_held),))

    require(promises <= gone,
            "%d fired intentions' own events are not in the set the engine "
            "abstains on, although none of them is readable"
            % (len(promises - gone),))
    require_equal(len(gone), state.forgetting.count,
                  "the record counts %d losses while read(t) abstains on %d — "
                  "the record is not the set of things it lost"
                  % (state.forgetting.count, len(gone)))
    require(state.forgetting.mass >= state.forgetting.count,
            "%d recorded losses carry %d mass"
            % (state.forgetting.count, state.forgetting.mass))
    require_equal(state.demotions + state.forgetting.count + l5.retained(state),
                  state.next_t,
                  "the ledger does not close over every logical time the engine "
                  "assigned, its own firings included")
    require(state.forgetting.count > len(promises),
            "the record carries %d losses against %d kept promises — with the "
            "promises stripped out it would read %d, and a record that IS the "
            "promises is measuring one thing where this asymmetry needs two"
            % (state.forgetting.count, len(promises),
               state.forgetting.count - len(promises)))

    # …while the armed neighbours regenerate byte-exact at the same cap.
    for iid in pending:
        t0 = _t0(b, iid)
        answer = l5.query(state, {"op": "read", "t": t0})
        require_equal(answer["status"], "answer",
                      "intention %d has not fired, so its pending entry still "
                      "regenerates its event — read(%d) abstained under exactly "
                      "the pressure its fired neighbours were booked under"
                      % (iid, t0))
        require_equal(answer["value"], {"payload": _intend_payload(b, iid),
                                       "t": t0},
                      "an unkept promise did not come back byte-exact from "
                      "read(%d)" % (t0,))

    # A promise cannot buy itself priority: declaring a weight stops it arming.
    plain = {"kind": "intend", "iid": 1, "cond": {"p": "kind", "v": "note"},
             "fire": {"kind": "fired", "text_id": 900}}
    weighted = dict(plain)
    weighted["importance"] = 9
    require(l5.arms(plain) is not None, "the control payload does not arm")
    require(l5.arms(weighted) is None,
            "an `intend` payload declaring `importance` still arms — then a "
            "promise could weigh more than 1 in the forgetting record and could "
            "outbid the episodes it displaces, which README-l5 §1.2's "
            "canonical-bytes rule is what forbids")

    # --- where there is room: the promise is taken back ----------------------
    prefix = b["payloads"][:PREFIX_EVENTS]
    cap = 4 * sum(event_cost(p) for p in prefix)
    roomy, refused = _replay(prefix, cap)
    require_equal(refused, [], "an in-budget write was refused on the prefix")

    fired_roomy = l5.fired_iids(roomy)
    pending_roomy = l5.pending_iids(roomy)
    require(fired_roomy and pending_roomy,
            "the prefix ended with %d fired and %d pending intentions — this "
            "direction needs both, or it asserts half an asymmetry"
            % (len(fired_roomy), len(pending_roomy)))
    require_equal(roomy.forgetting.count, 0,
                  "%d events were forgotten at four times the prefix's own "
                  "footprint, so nothing here distinguishes a release the budget "
                  "forced from one it did not" % (roomy.forgetting.count,))

    for iid in fired_roomy:
        t0 = _t0(b, iid)
        answer = l5.query(roomy, {"op": "read", "t": t0})
        require_equal(answer["status"], "answer",
                      "intention %d fired at a cap with room to spare and its "
                      "own `intend` event is gone: nothing forced that drop, and "
                      "an engine that releases unconditionally is BOUNDARY.log "
                      "line 32's Stage-C defect — a Layer-1 regression no §5 L5 "
                      "clause can see" % (iid,))
        require_equal(answer["value"], {"payload": _intend_payload(b, iid),
                                       "t": t0},
                      "a kept promise taken back did not come back byte-exact "
                      "from read(%d)" % (t0,))
        require_equal(answer["provenance"]["kind"], "recall",
                      "intention %d's own event is readable but not from a "
                      "stored episode — firing consumes the derivation that "
                      "regenerated it, so a `derive` here means something else "
                      "is still claiming to rebuild a promise that has been kept"
                      % (iid,))

    for iid in pending_roomy:
        t0 = _t0(b, iid)
        answer = l5.query(roomy, {"op": "read", "t": t0})
        require_equal(answer["value"], {"payload": _intend_payload(b, iid),
                                       "t": t0},
                      "an unkept promise did not come back byte-exact from "
                      "read(%d) at a generous cap" % (t0,))
        require_equal(answer["provenance"]["kind"], "derive",
                      "intention %d is still pending and its event was answered "
                      "from a stored episode — arming releases it, and a "
                      "`recall` here means the cells were spent twice" % (iid,))

    lost = [t for t in range(roomy.next_t)
            if l5.query(roomy, {"op": "read", "t": t})["status"] == "abstain"]
    require_equal(lost, [],
                  "%d events are unreadable on a prefix replayed at four times "
                  "its own footprint (§5 L1's F = 1000 is a claim about an "
                  "engine in budget, and prospection does not get to spend it)"
                  % (len(lost),))


# ---- 4. docs are checked, not trusted ---------------------------------------

def _spaced(n):
    """The project's thousands form: `18724` -> `18 724`."""
    out = str(n)
    parts = []
    while len(out) > 3:
        parts.insert(0, out[-3:])
        out = out[:-3]
    parts.insert(0, out)
    return " ".join(parts)


def trial_the_blocking_numbers_are_the_ones_the_documents_state():
    """R6 clause 3 from the enforcing side: this file computes, the note reports.

    *"Where a document states a quantity that a trial also computes, the trial's
    value is the enforced one."* `README-l5 §4`'s dated non-capability note carries
    the numbers this file measures — the form `README-l4 §4` took for the 26‰ cue
    reach one layer down — so the note is checked against the run rather than
    trusted, and a drift in either direction is a red trial rather than a diff
    nobody reads.

    The class index is checked for the same reason `strain/l5`'s existing file
    checks its own: a README that names a file which does not exist, or omits one
    that does, has stopped being a record.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    index = os.path.join(os.path.dirname(here), "README.md")
    with open(index, "r", encoding="utf-8") as fh:
        text = fh.read()
    require("l5/t_prospection_blocking_seam.py" in text,
            "trials/strain/README.md does not index this file")
    require(os.path.isfile(os.path.join(here,
                                        "t_prospection_blocking_seam.py")),
            "the indexed strain file is not where the index says it is")

    state, _budget, b = _at_the_gate()
    reached, answerable, permille = _reach()
    tiers = len(l5.pending_iids(state)) + len(l5.fired_iids(state))

    readme = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(here))),
                          "core", "layers", "README-l5.md")
    with open(readme, "r", encoding="utf-8") as fh:
        note = fh.read()
    for figure in ("%s of %s" % (_spaced(reached), _spaced(answerable)),
                   "%d‰" % (permille,),
                   _spaced(len(l5.fired_iids(state))),
                   _spaced(len(l5.pending_iids(state))),
                   _spaced(tiers)):
        require(figure in note,
                "core/layers/README-l5.md does not carry the measured figure "
                "%r. Under R6 clause 3 this trial's value is the enforced one "
                "and the note is what has to say it: cue reach %s of %s = %d‰, "
                "over %s prospection-tier events none of which any cue reaches"
                % (figure, _spaced(reached), _spaced(answerable), permille,
                   _spaced(tiers)))
